# Generated by Django 4.2 on 2024-10-16 23:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("language", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "provider",
                "db_table_comment": "Stores data about providers, including contact details, language, and currency preferences.",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "geojson",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="app.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Area",
                "verbose_name_plural": "Service Areas",
                "db_table": "service_area",
                "db_table_comment": "Stores service area polygons and pricing information linked to providers.",
                "ordering": ["name", "price"],
            },
        ),
    ]
